### ISSUE TITLE
Add dynamo builds to builds page

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/speckleworks-website#10]
Since now we've got CI going for Dynamo (https://github.com/speckleworks/SpeckleDynamo/pull/23), we should [add links to the build artefacts same as for SpeckleRhino](https://speckle.works/builds/). 

This will obviously mean that later on we should take care on how we distribute the dynamo plugin - @teocomi added it to the package manager, we have the fresh builds from appveyor thanks to @pearswj and @alvpickmans, etc.

**Comment by alvpickmans** [comment]
Might be a good time to speak about versioning? Not sure if there's something in placed already.
For the builds/artifacts, I kind of like how Dynamo names them: `{ProjectName}.{LatestEstableVersion}.{Timestamp}.{extension}`

[http://dynamobuilds.com/](http://dynamobuilds.com/)

**Comment by pearswj** [comment]
✅ speckleworks/speckleworks-website@310ddef1b65657b675a67878395d59e69f70edb6

**Comment by pearswj** [comment]
@alvpickmans Sorry, closed this without addressing your comment. Displaying the actual artifact names on https://speckle.works/builds requires too many API calls so I just linked to the artifacts tab on the AppVeyor build page. Please go ahead and open another issue/bring this up on Slack if you want to discuss versioning for SpeckleDynamo :+1:

**Comment by didimitrie** [comment]
and this has been discussed previously, but not really implemented in plugins: 
- https://github.com/speckleworks/SpeckleRhino/issues/97
- https://github.com/speckleworks/SpeckleOrg/issues/7

Server and Core are at `1.x.x`, but plugins not yet really. I think SpeckleRhino is waiting to get out of beta to get the `1.0.0` tag, and SpeckleDynamo too  maybe?

**Comment by alvpickmans** [comment]
@pearswj @didimitrie thanks for the input, I will have a read and keep the discussion on Slack if necessary
