### ISSUE TITLE
Links to Model Viewer app in Speckle Docs are broken

### ISSUE THREAD

**Issue by radumg** [speckleworks/speckleworks-website#5]
The `Model Viewer` documentation page here https://speckle.works/doc/onlineviewer/ lists a couple of links to example streams in the viewer ;
- https://app.speckle.works/viewer/?rkp4LVi-b
- https://app.speckle.works/viewer/?SJQTff1fW,Hyl7AQ1GZ
- https://app.speckle.works/viewer/?H1YX_M4GZ,Sk8rGmNfb
- https://app.speckle.works/viewer/?Hk8lgC8W-,BJqlzkPZb

Another page with same broken links is here :
https://discourse.speckle.works/t/speckle-model-viewer/39

Links are all broken, with 404s.
Swapping `app.speckle` for `s003.speckle` also didn't work - can't remember what the latest url is @didimitrie ?

**Comment by radumg** [comment]
Update : found the links in a Discourse page :
https://s003.speckle.works/view/?SJQTff1fW,Hyl7AQ1GZ

**Comment by didimitrie** [comment]
Yeahs, they're old and outdated those docs and links... I think we'll move away from them slowly, ie completely remove that section from the website (have just tutorials now and then in the blog section) and migrate to repo wikis for more detailed instructions, as they're easier to maintain

**Comment by radumg** [comment]
Sounds like a reasonable plan, these links would still be relevant on those new pages though, so i assume useful to merge ?

**Comment by didimitrie** [comment]
i completely missed the pr. Yes go ahead!
